### PR TITLE
Adding pins to Budapest guide map

### PR DESCRIPTION
**Pull request by MikeRogers0**
I also set `scrollwheel` to false so that when a user scrolls up and
down the page it doesn't stop and start zooming in and out the map.

image

scrolling-is-nice

### CODE REVIEW

**Comment by necccc** [comment]
Nice one, thanks! :)

**Comment by gergelyke** [comment]
With this the previous PR was killed :(

https://github.com/JSConfBp/jsconfbp.github.io/pull/3/files

**Comment by gergelyke** [comment]
Also, there is a typo Roobach -> Roombach

**Comment by necccc** [comment]
fixed, the prev PR and typo

**Pull request merged**
